dist: bionic
language: generic
env:
  global:
  - LANG=C
  - LC_ALL=C
before_script:
- sudo apt-get -y update
- sudo apt-get -y install texlive-full python-pygments
script:
# PRIMO ANNO
- cd "Primo Anno" && cd "Algebra Lineare e Geometria" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape Algebra-geometria.tex && cd .. && cd ..
- cd "Primo Anno" && cd "Algoritmi e Strutture Dati" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape algoritmi.tex && cd .. && cd ..
- cd "Primo Anno" && cd "Analisi Matematica" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape analisi.tex && cd .. && cd ..
- cd "Primo Anno" && cd "Architettura degli Elaboratori" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape architettura.tex && cd .. && cd ..
#- cd "Primo Anno" && cd "Fondamenti" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape appunti.tex && cd .. && cd ..
# SECONDO ANNO
- cd "Secondo Anno" && cd "Analisi e Progettazione del Software" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape aps.tex && cd .. && cd ..
- cd "Secondo Anno" && cd "Basi di Dati" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape basi.tex && cd .. && cd ..
- cd "Secondo Anno" && cd "Fisica" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape fisica.tex && cd .. && cd ..
- cd "Secondo Anno" && cd "Linguaggi di Programmazione" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape linguaggi-di-programmazione.tex && cd .. && cd ..
- cd "Secondo Anno" && cd "Linguaggi e Computabilità" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape linguaggi-e-computabilità.tex && cd .. && cd ..
- cd "Secondo Anno" && cd "Metodi algebrici per l'informatica" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape metodi-algebrici-per-informatica.tex && cd .. && cd ..
- cd "Secondo Anno" && cd "Probabilità e Statistica per l'Informatica" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape statistica.tex && cd .. && cd ..
- cd "Secondo Anno" && cd "Reti e Sistemi Operativi" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape rso.tex && cd .. && cd ..
# TERZO ANNO
- cd "Terzo Anno" && cd "Analisi e Progetto di Algoritmi" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape algoritmi2.tex && cd .. && cd ..
- cd "Terzo Anno" && cd "Elementi di Bioinformatica" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape bioinformatica.tex && cd .. && cd ..
- cd "Terzo Anno" && cd "Programmazione C++" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape cpp.tex && cd .. && cd ..
- cd "Terzo Anno" && cd "Ricerca Operativa e Pianificazione delle Risorse" && xelatex -synctex=1 -interaction=nonstopmode --shell-escape ro.tex && cd .. && cd ..
